version: '3'

services:
  sodbot:
    restart: always
    build: .
    volumes:
      - ./data:/db/sd2.struktur.online
    ports:
      - "8080"
    environment:
      DOMAIN: sd2.struktur.online
      VIRTUAL_HOST: sd2.struktur.online
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: sd2.struktur.online
      LETSENCRYPT_EMAIL: mirko.friedrich@blandland.de
    networks:
        - default
        - backend
networks:
    backend:
    default:
        external:
            name: web
volumes:
  db-data: