# version: '3'

# services:
#   sodbot:
#     restart: always
#     build: .
#     volumes:
#       - ./data:/db/sd2.struktur.online
#     ports:
#       - "8080"
#     environment:
#       DOMAIN: ${DOMAIN}
#       VIRTUAL_HOST: ${DOMAIN}
#       VIRTUAL_PORT: 8080
#       LETSENCRYPT_HOST: ${DOMAIN}
#       LETSENCRYPT_EMAIL: vesecky.lukas7@gmail.com
#     networks:
#         - default
# networks:
#     default:
#         external:
#             name: web
