# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: BLEEDING EDGE DEPLOY

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
        
    - name: create config files
      uses: schdck/create-env-json@v2
      with:
        file-name: config.json
        prefix: $
        logFileName: log.txt
        discordToken: ${{ secrets.PROD_DISCORD_TOKEN }}
        sqluser: kurios
        sqlpassword: ${{ secrets.SQLPASSWORD }}
        database: sodbot-prod
        
    - name: build and publish container
      uses: docker/build-push-action@v1
      with:
        context: .
        tags: bleeding
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        repository: sd2-nerd-hq/sodbot
        
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sodbot-bleeding-edge'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_297616ade86c41a6a042f3f36bf10658 }}
        images: 'ghcr.io/sd2-nerd-hq/sodbot:bleeding'
